name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: xd-ecr
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: haiktpm/xd-working-trial-helm-chart
        
    - name: update manifest
      run: |
        cd charts-xd-trial
        ls -la
        envsubst < values/xd-trial-values.yaml.template > values/xd-trial-values.yaml
        
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
      with:
        source-directory: 'values'
        destination-github-username: 'haiktpm'
        destination-repository-name: 'xd-working-trial-helm-chart'
        user-email: haitv2809@gmail.com
        target-branch: main
          
