name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: xd-ecr
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: haiktpm/xd-working-trial-helm-chart
    - name: deploy to EKS
      run: |
        cd charts-xd-trial/values
        ls -la
        envsubst < xd-trial-values.yaml.template > xd-trial-values.yaml
        git add .
        git config user.email "haitv2809@gmail.com" && git config user.name "haiktpm" && git commit -am "${{ github.event.head_commit.message }}"
        git push
